/* eslint-disable camelcase */

import '@/globals.css'

import { ReactNode } from 'react'
import { Roboto_Flex } from 'next/font/google'
import TopBar from '@/components/home/TopBar'
import { homeMenuItens } from '@/lib/HomeItens'

const robotoFlex = Roboto_Flex({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className="dark">
      <body className={robotoFlex.className}>
        <TopBar pageTitle="Portfolio" menuItens={homeMenuItens} />
        {children}
      </body>
    </html>
  )
}
